algoritmo "semnome"
// Função :trocar variaveis de lugar
// Autor : leticia franca nery
// Data : 21/03/2021
// Seção de Declarações 
var

a,b,aux:inteiro

inicio
escreval("digite um valor para a:")
leia(a)

escreval("digite um valor para b: ")
leia(b)

//processamento

aux <- a
a <- b
b <- aux

escreval("VALORES TROCADOS")

escreval("valor de a:",a)

escreval("valor de b:",b)
// Seção de Comandos
fimalgoritmo
